name: flake8_lint

on:
  push:
    # Only run if,
    paths:
      # Changes in python files
      - '*.py'
    branches:
      - master
  pull_request:
    # Only run if,
    paths:
      # Changes in python files
      - '*.py'
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup flake8 annotations  # To annotate the errors in the pull request
      uses: rbialon/flake8-annotations@v1
    - name: Lint with flake8
      # Check for only changed files, rather than the entire repository
      run: |
        pip install flake8
        git diff HEAD^ | flake8 --diff
