name: Linter

on:
  push:
    # Only run if,
    paths:
      # Changes in python files
      - "**.py"
    branches:
      - master
  pull_request:
    # Only run if,
    paths:
      # Changes in python
      - "**.py"
    branches:
      - master

jobs:
   lint:

    steps:
      - name: Testing with flake8
        uses: TrueBrain/actions-flake8@master
